import './CSVReader.scss';
import { ParseResult } from 'papaparse';
import { Button, Form, InputGroup } from 'react-bootstrap';
import { useCSVReader } from 'react-papaparse';

interface IProps {
  onUploadAccepted: (results: ParseResult<string[]>) => void;
}

const CSVReader = ({ onUploadAccepted }: IProps) => {
  const { CSVReader } = useCSVReader();

  return (
    <CSVReader onUploadAccepted={onUploadAccepted}>
      {({ getRootProps, acceptedFile, ProgressBar }: any) => (
        <div className="csv-reader">
          <div>
            Please input the index.csv file that was previous generated by the{' '}
            <a href="https://github.com/lbeder/google-voice-merger" target="_blank" rel="noopener noreferrer">
              Google Voice Merger
            </a>{' '}
            tool:
          </div>
          <InputGroup>
            <Form.Control
              type="input"
              placeholder="CSV file"
              defaultValue={(acceptedFile && acceptedFile.name) || ''}
            />
            <Button {...getRootProps()}>Browse file</Button>

            <ProgressBar className="progress-bar" />
          </InputGroup>
        </div>
      )}
    </CSVReader>
  );
};

export default CSVReader;
