import './CSVReader.scss';
import moment, { Moment } from 'moment';
import { ParseResult } from 'papaparse';
import { Button, Form, InputGroup } from 'react-bootstrap';
import { useCSVReader } from 'react-papaparse';

export class Entry {
  public originalPhoneNumber: string;
  public firstDate: Moment;
  public lastDate: Moment;
  public phoneNumber: string;
  public name: string;
  public match: number;
  public path: string;
  public fileSize: number;
  public mediaSize: number;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(result: Record<string, any>) {
    this.originalPhoneNumber = result['phone number (html)'];
    this.firstDate = moment(result['first date']);
    this.lastDate = moment(result['last date']);
    this.phoneNumber = result['phone number (vcf)'];
    this.name = result['name (vcf)'];
    this.match = Number(result['match length']);
    this.path = result['path'];
    this.fileSize = Number(result['file size']);
    this.mediaSize = Number(result['media size']);
  }
}

interface Props {
  onUploadAccepted: (results: ParseResult<string[]>) => void;
  validator: (file: File) => void;
}

/* eslint-disable @typescript-eslint/no-explicit-any */
interface CSVChildProps {
  getRootProps: any;
  acceptedFile: any;
  ProgressBar: any;
}
/* eslint-enable @typescript-eslint/no-explicit-any */

const CSVReader = ({ onUploadAccepted, validator }: Props) => {
  const { CSVReader } = useCSVReader();

  return (
    <CSVReader config={{ header: true, noProgressBar: true }} onUploadAccepted={onUploadAccepted} validator={validator}>
      {({ getRootProps, acceptedFile, ProgressBar }: CSVChildProps) => (
        <div className="csv-reader">
          <div>
            Please input the index.csv file that was previous generated by the{' '}
            <a href="https://github.com/lbeder/google-voice-merger" target="_blank" rel="noopener noreferrer">
              Google Voice Merger
            </a>{' '}
            tool:
          </div>
          <InputGroup>
            <Form.Control
              type="input"
              placeholder="CSV file"
              defaultValue={(acceptedFile && acceptedFile.name) || ''}
            />
            <Button {...getRootProps()}>Browse file</Button>
          </InputGroup>

          <ProgressBar className="progress-bar" />
        </div>
      )}
    </CSVReader>
  );
};

export default CSVReader;
